/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/attachments/card/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_attachments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_link_attachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_attachment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_boards"];
        put?: never;
        post: operations["create_board"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_board_by_slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_board"];
        put: operations["update_board"];
        post?: never;
        delete: operations["delete_board"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_card"];
        put: operations["update_card"];
        post?: never;
        delete: operations["delete_card"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_actions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cards_list_comments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add_label"];
        delete: operations["remove_label"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add_member"];
        delete: operations["remove_member"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["move_card"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}/task-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_task_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}/task-lists/{tlid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_task_list"];
        post?: never;
        delete: operations["delete_task_list"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}/task-lists/{tlid}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}/task-lists/{tlid}/tasks/{tid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_task"];
        post?: never;
        delete: operations["delete_task"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/card/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_comments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_comment"];
        post?: never;
        delete: operations["delete_comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_favorites"];
        put?: never;
        post: operations["create_favorite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_favorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_label"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels/board/{board_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_labels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_label"];
        post?: never;
        delete: operations["delete_label"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_list"];
        put: operations["update_list"];
        post?: never;
        delete: operations["delete_list"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Action: {
            /** Format: uuid */
            board_id?: string | null;
            /** Format: uuid */
            card_id: string;
            created_at: string;
            data: string;
            /** Format: uuid */
            id: string;
            type: string;
            /** Format: uuid */
            user_id?: string | null;
        };
        Attachment: {
            /** Format: uuid */
            card_id: string;
            created_at: string;
            file_path?: string | null;
            /** Format: uuid */
            id: string;
            link_url?: string | null;
            mime_type?: string | null;
            name: string;
            /** Format: int64 */
            size?: number | null;
            type: string;
            /** Format: uuid */
            user_id: string;
        };
        Board: {
            created_at: string;
            /** Format: uuid */
            created_by: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: double */
            position: number;
            slug: string;
            updated_at: string;
        };
        Card: {
            /** Format: uuid */
            board_id: string;
            created_at: string;
            /** Format: uuid */
            created_by: string;
            description?: string | null;
            due_date?: string | null;
            /** Format: uuid */
            id: string;
            is_closed: boolean;
            is_due_completed: boolean;
            /** Format: uuid */
            list_id: string;
            name: string;
            /** Format: double */
            position: number;
            updated_at: string;
        };
        CardWithMembers: {
            /** Format: uuid */
            board_id: string;
            checklists: components["schemas"]["TaskListWithTasks"][];
            /** Format: int64 */
            comments_count: number;
            created_at: string;
            /** Format: uuid */
            created_by: string;
            description?: string | null;
            due_date?: string | null;
            /** Format: uuid */
            id: string;
            is_closed: boolean;
            is_due_completed: boolean;
            labels: components["schemas"]["Label"][];
            /** Format: uuid */
            list_id: string;
            members: components["schemas"]["UserResponse"][];
            name: string;
            /** Format: double */
            position: number;
            updated_at: string;
        };
        Comment: {
            /** Format: uuid */
            card_id: string;
            created_at: string;
            /** Format: uuid */
            id: string;
            text: string;
            updated_at: string;
            /** Format: uuid */
            user_id: string;
        };
        CommentWithUser: {
            /** Format: uuid */
            card_id: string;
            created_at: string;
            /** Format: uuid */
            id: string;
            text: string;
            updated_at: string;
            user?: null | components["schemas"]["UserResponse"];
            /** Format: uuid */
            user_id: string;
        };
        CreateBoardRequest: {
            name: string;
        };
        CreateCardRequest: {
            description?: string | null;
            /** Format: uuid */
            list_id: string;
            name: string;
        };
        CreateCommentRequest: {
            /** Format: uuid */
            card_id: string;
            text: string;
        };
        CreateFavoriteRequest: {
            /** Format: uuid */
            board_id?: string | null;
            /** Format: uuid */
            card_id?: string | null;
        };
        CreateLabelRequest: {
            /** Format: uuid */
            board_id: string;
            color?: string | null;
            name: string;
        };
        CreateListRequest: {
            /** Format: uuid */
            board_id: string;
            name?: string | null;
        };
        CreateTaskListRequest: {
            /** Format: uuid */
            card_id: string;
            name: string;
        };
        CreateTaskRequest: {
            name: string;
        };
        Favorite: {
            /** Format: uuid */
            board_id?: string | null;
            /** Format: uuid */
            card_id?: string | null;
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
        };
        Label: {
            /** Format: uuid */
            board_id: string;
            color: string;
            created_at: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: double */
            position: number;
            updated_at: string;
        };
        List: {
            /** Format: uuid */
            board_id: string;
            color?: string | null;
            created_at: string;
            /** Format: uuid */
            id: string;
            name?: string | null;
            /** Format: double */
            position: number;
            type: string;
            updated_at: string;
        };
        ListWithCards: {
            /** Format: uuid */
            board_id: string;
            cards: components["schemas"]["CardWithMembers"][];
            color?: string | null;
            created_at: string;
            /** Format: uuid */
            id: string;
            name?: string | null;
            /** Format: double */
            position: number;
            type: string;
            updated_at: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MoveCardRequest: {
            /** Format: uuid */
            list_id: string;
            /** Format: double */
            position: number;
        };
        Notification: {
            /** Format: uuid */
            action_id?: string | null;
            /** Format: uuid */
            card_id?: string | null;
            created_at: string;
            data: string;
            /** Format: uuid */
            id: string;
            is_read: boolean;
            type: string;
            /** Format: uuid */
            user_id: string;
        };
        RegisterRequest: {
            email: string;
            name: string;
            password: string;
        };
        Task: {
            /** Format: uuid */
            assignee_id?: string | null;
            created_at: string;
            /** Format: uuid */
            id: string;
            is_completed: boolean;
            name: string;
            /** Format: double */
            position: number;
            /** Format: uuid */
            task_list_id: string;
            updated_at: string;
        };
        TaskList: {
            /** Format: uuid */
            card_id: string;
            created_at: string;
            hide_completed: boolean;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: double */
            position: number;
            updated_at: string;
        };
        TaskListWithTasks: {
            /** Format: uuid */
            card_id: string;
            created_at: string;
            hide_completed: boolean;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: double */
            position: number;
            tasks: components["schemas"]["Task"][];
            updated_at: string;
        };
        UpdateBoardRequest: {
            name?: string | null;
            /** Format: double */
            position?: number | null;
        };
        UpdateCardRequest: {
            description?: string | null;
            due_date?: string | null;
            is_closed?: boolean | null;
            is_due_completed?: boolean | null;
            /** Format: uuid */
            list_id?: string | null;
            name?: string | null;
            /** Format: double */
            position?: number | null;
        };
        UpdateCommentRequest: {
            text: string;
        };
        UpdateLabelRequest: {
            color?: string | null;
            name?: string | null;
            /** Format: double */
            position?: number | null;
        };
        UpdateListRequest: {
            color?: string | null;
            name?: string | null;
            /** Format: double */
            position?: number | null;
        };
        UpdateTaskRequest: {
            /** Format: uuid */
            assignee_id?: string | null;
            is_completed?: boolean | null;
            name?: string | null;
            /** Format: double */
            position?: number | null;
        };
        User: {
            created_at: string;
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
            role: string;
            updated_at: string;
        };
        UserResponse: {
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_attachments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of attachments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_link_attachment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Link attachment data */
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Link attachment created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_attachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Attachment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Attachment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_boards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of boards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_board: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardRequest"];
            };
        };
        responses: {
            /** @description Board created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_board_by_slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board with lists and members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_board: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board with lists and members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_board: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBoardRequest"];
            };
        };
        responses: {
            /** @description Board updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_board: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_card: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardRequest"];
            };
        };
        responses: {
            /** @description Card created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCardRequest"];
            };
        };
        responses: {
            /** @description Card updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_actions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of actions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cards_list_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_label: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description Label data */
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Label added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_label: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description Label data */
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Label removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description Member data */
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Member added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description Member data */
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Member removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    move_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCardRequest"];
            };
        };
        responses: {
            /** @description Card moved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_task_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskListRequest"];
            };
        };
        responses: {
            /** @description Task list created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_task_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
                /** @description Task list ID */
                tlid: string;
            };
            cookie?: never;
        };
        /** @description Task list update data */
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Task list updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task list not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_task_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
                /** @description Task list ID */
                tlid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task list deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task list not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
                /** @description Task list ID */
                tlid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Task created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
                /** @description Task list ID */
                tlid: string;
                /** @description Task ID */
                tid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Task updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                id: string;
                /** @description Task list ID */
                tlid: string;
                /** @description Task ID */
                tid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_comment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card ID */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_favorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of favorites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_favorite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFavoriteRequest"];
            };
        };
        responses: {
            /** @description Favorite created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_favorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Favorite ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorite deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Favorite not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_label: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLabelRequest"];
            };
        };
        responses: {
            /** @description Label created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_labels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_label: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Label ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLabelRequest"];
            };
        };
        responses: {
            /** @description Label updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Label not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_label: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Label ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Label deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Label not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListRequest"];
            };
        };
        responses: {
            /** @description List created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description List ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List with cards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description List not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description List ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateListRequest"];
            };
        };
        responses: {
            /** @description List updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description List not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description List ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description List not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
