// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiKeyResponse = { id: string, name: string, prefix: string, expires_at: String | null, last_used_at: String | null, created_at: String, is_active: boolean, };
