// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { id: string, card_id: string, user_id: string, name: string, type: string, file_path: string | null, link_url: string | null, size: bigint | null, mime_type: string | null, created_at: string, };
