// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardWithMembers } from "./CardWithMembers";

export type ListWithCards = { id: string, board_id: string, name: string | null, position: number, type: string, color: string | null, cards: Array<CardWithMembers>, created_at: string, updated_at: string, };
