// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";

export type TaskListWithTasks = { id: string, card_id: string, name: string, position: number, hide_completed: boolean, tasks: Array<Task>, created_at: string, updated_at: string, };
