use utoipa::OpenApi;

use crate::handlers;
use crate::models;

#[derive(OpenApi)]
#[openapi(
    paths(
        handlers::auth::register,
        handlers::auth::login,
        handlers::auth::logout,
        handlers::auth::me,
        handlers::board::list_boards,
        handlers::board::create_board,
        handlers::board::get_board,
        handlers::board::update_board,
        handlers::board::delete_board,
        handlers::board::get_board_by_slug,
        handlers::card::create_card,
        handlers::card::get_card,
        handlers::card::update_card,
        handlers::card::delete_card,
        handlers::card::move_card,
        handlers::card::add_member,
        handlers::card::remove_member,
        handlers::card::add_label,
        handlers::card::remove_label,
        handlers::card::create_task_list,
        handlers::card::update_task_list,
        handlers::card::delete_task_list,
        handlers::card::create_task,
        handlers::card::update_task,
        handlers::card::delete_task,
        handlers::card::list_comments,
        handlers::card::list_actions,
        handlers::list::create_list,
        handlers::list::get_list,
        handlers::list::update_list,
        handlers::list::delete_list,
        handlers::label::create_label,
        handlers::label::list_labels,
        handlers::label::update_label,
        handlers::label::delete_label,
        handlers::comment::create_comment,
        handlers::comment::list_comments,
        handlers::comment::update_comment,
        handlers::comment::delete_comment,
        handlers::attachment::list_attachments,
        handlers::attachment::create_link_attachment,
        handlers::attachment::delete_attachment,
        handlers::favorite::list_favorites,
        handlers::favorite::create_favorite,
        handlers::favorite::delete_favorite,
        handlers::search::search,
        handlers::list_users,
    ),
    components(
        schemas(
            models::board::Board,
            models::board::CreateBoardRequest,
            models::board::UpdateBoardRequest,
            models::card::Card,
            models::card::CreateCardRequest,
            models::card::UpdateCardRequest,
            models::card::CardWithMembers,
            models::card::MoveCardRequest,
            models::list::List,
            models::list::CreateListRequest,
            models::list::UpdateListRequest,
            models::list::ListWithCards,
            models::label::Label,
            models::label::CreateLabelRequest,
            models::label::UpdateLabelRequest,
            models::comment::Comment,
            models::comment::CreateCommentRequest,
            models::comment::UpdateCommentRequest,
            models::comment::CommentWithUser,
            models::attachment::Attachment,
            models::action::Action,
            models::checklist::TaskList,
            models::checklist::Task,
            models::checklist::TaskListWithTasks,
            models::checklist::CreateTaskListRequest,
            models::checklist::CreateTaskRequest,
            models::checklist::UpdateTaskRequest,
            models::favorite::Favorite,
            models::favorite::CreateFavoriteRequest,
            models::notification::Notification,
            models::user::User,
            models::user::RegisterRequest,
            models::user::LoginRequest,
            models::user::UserResponse,
        )
    ),
    tags(
        (name = "auth", description = "Authentication"),
        (name = "boards", description = "Board management"),
        (name = "cards", description = "Card management"),
        (name = "lists", description = "List management"),
        (name = "labels", description = "Label management"),
        (name = "comments", description = "Comment management"),
        (name = "attachments", description = "Attachment management"),
        (name = "favorites", description = "Favorite management"),
        (name = "search", description = "Search"),
        (name = "users", description = "User management"),
    )
)]
pub struct ApiDoc;
