// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = { id: string, card_id: string, board_id: string | null, user_id: string | null, type: string, data: string, created_at: string, };
