// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiKey = { id: string, user_id: string, name: string, prefix: string, expires_at: string | null, last_used_at: string | null, created_at: string, is_active: boolean, };
