// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Board = { id: string, name: string, position: number, slug: string, created_by: string, created_at: string, updated_at: string, };
