// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Label } from "./Label";
import type { TaskListWithTasks } from "./TaskListWithTasks";
import type { UserResponse } from "./UserResponse";

export type CardWithMembers = { id: string, board_id: string, list_id: string, position: number, name: string, description: string | null, start_date: string | null, due_date: string | null, is_due_completed: boolean, is_closed: boolean, created_by: string, members: Array<UserResponse>, labels: Array<Label>, comments_count: bigint, checklists: Array<TaskListWithTasks>, created_at: string, updated_at: string, };
