// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Card = { id: string, board_id: string, list_id: string, position: number, name: string, description: string | null, due_date: string | null, is_due_completed: boolean, is_closed: boolean, created_by: string, created_at: string, updated_at: string, };
