// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserResponse } from "./UserResponse";

export type CommentWithUser = { id: string, card_id: string, user_id: string, user: UserResponse | null, text: string, created_at: string, updated_at: string, };
