// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateFavoriteRequest = { board_id: string | null, card_id: string | null, };
