// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notification = { id: string, user_id: string, type: string, data: string, is_read: boolean, card_id: string | null, action_id: string | null, created_at: string, };
