// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Task = { id: string, task_list_id: string, name: string, position: number, is_completed: boolean, assignee_id: string | null, created_at: string, updated_at: string, };
