// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskList = { id: string, card_id: string, name: string, position: number, hide_completed: boolean, created_at: string, updated_at: string, };
