// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCardRequest = { name: string | null, description: string | null, position: number | null, start_date: string | null, due_date: string | null, is_due_completed: boolean | null, is_closed: boolean | null, list_id: string | null, };
