// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateTaskRequest = { name: string | null, is_completed: boolean | null, position: number | null, assignee_id: string | null, };
