// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: string, username: string, name: string, role: string, created_at: string, updated_at: string, };
